#ifndef _COMMON_H_
#define _COMMON_H_

typedef enum{
    MT_NULL = 0x00,
    MT_LANDING_DATA,
    MT_LANDING_RESULT,
    MT_REGISTER_DATA,
    MT_REGISTER_RESULT,
    MT_RETURNTHELIST_DATA,
    MT_CHATREQUESTS_DATA,
    MT_CHATREQUESTS_RESULT,
    MT_SENDMESSAGE_MESSAGE,
    MT_SENDMESSAGE_DATA,
    MT_GETMESSAGE_MESSAGE,
    MT_GETMESSAGE_DATA
}MsgType;

typedef enum{
    ET_CHANGETHELIST = 0x01,
    ET_CHATREQUEST,
    ET_CHATREQUESTRESULT
}EventType;

#endif //_COMMON_H_